-- MySQL Script generated by MySQL Workbench
-- Sun Sep 18 20:02:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema os_oficina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema os_oficina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `os_oficina` DEFAULT CHARACTER SET utf8 ;
USE `os_oficina` ;

-- -----------------------------------------------------
-- Table `os_oficina`.`valor_peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`valor_peca` (
  `idvalor_peca` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `radiador` DECIMAL(50,2) NOT NULL,
  `valvula` DECIMAL(50,2) NOT NULL,
  `camara_ar` DECIMAL(50,2) NOT NULL,
  `farol_milha` DECIMAL(50,2) NOT NULL,
  `mao_de_obra_idmao_de_obra` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvalor_peca`),
  UNIQUE INDEX `idvalor_peca_UNIQUE` (`idvalor_peca` ASC) VISIBLE,
  INDEX `fk_valor_peca_mao_de_obra1_idx` (`mao_de_obra_idmao_de_obra` ASC) VISIBLE,
  CONSTRAINT `fk_valor_peca_mao_de_obra1`
    FOREIGN KEY (`mao_de_obra_idmao_de_obra`)
    REFERENCES `os_oficina`.`mao_de_obra` (`idmao_de_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`mao_de_obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`mao_de_obra` (
  `idmao_de_obra` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `motor` DECIMAL(50,2) NOT NULL,
  `parachoque` DECIMAL(50,2) NOT NULL,
  `pneu` DECIMAL(50,2) NOT NULL,
  `valor_peca_idvalor_peca` INT UNSIGNED NOT NULL,
  `ordem_de_servico_id_ordem_de_servico` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmao_de_obra`),
  UNIQUE INDEX `idmao_de_obra_UNIQUE` (`idmao_de_obra` ASC) VISIBLE,
  INDEX `fk_mao_de_obra_valor_peca1_idx` (`valor_peca_idvalor_peca` ASC) VISIBLE,
  INDEX `fk_mao_de_obra_ordem_de_servico1_idx` (`ordem_de_servico_id_ordem_de_servico` ASC) VISIBLE,
  CONSTRAINT `fk_mao_de_obra_valor_peca1`
    FOREIGN KEY (`valor_peca_idvalor_peca`)
    REFERENCES `os_oficina`.`valor_peca` (`idvalor_peca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mao_de_obra_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id_ordem_de_servico`)
    REFERENCES `os_oficina`.`ordem_de_servico` (`id_ordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`n_os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`n_os` (
  `idn_numero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_os` DATE NOT NULL,
  `valor` DECIMAL(1000,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data_conclusao` DATE NOT NULL,
  PRIMARY KEY (`idn_numero`),
  UNIQUE INDEX `idn_os_UNIQUE` (`idn_numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`os`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`os` (
  `id_codigo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `n_os_idn_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_codigo`),
  UNIQUE INDEX `idos_UNIQUE` (`id_codigo` ASC) VISIBLE,
  INDEX `fk_os_n_os1_idx` (`n_os_idn_numero` ASC) VISIBLE,
  CONSTRAINT `fk_os_n_os1`
    FOREIGN KEY (`n_os_idn_numero`)
    REFERENCES `os_oficina`.`n_os` (`idn_numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`ordem_de_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`ordem_de_servico` (
  `id_ordem_de_servico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mao_de_obra_idmao_de_obra` INT UNSIGNED NOT NULL,
  `os_id_codigo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_ordem_de_servico`),
  UNIQUE INDEX `id_UNIQUE` (`id_ordem_de_servico` ASC) VISIBLE,
  INDEX `fk_ordem_de_servico_mao_de_obra1_idx` (`mao_de_obra_idmao_de_obra` ASC) VISIBLE,
  INDEX `fk_ordem_de_servico_os1_idx` (`os_id_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_ordem_de_servico_mao_de_obra1`
    FOREIGN KEY (`mao_de_obra_idmao_de_obra`)
    REFERENCES `os_oficina`.`mao_de_obra` (`idmao_de_obra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_de_servico_os1`
    FOREIGN KEY (`os_id_codigo`)
    REFERENCES `os_oficina`.`os` (`id_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`revisao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`revisao` (
  `id_revisao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordem_de_servico_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_revisao`),
  UNIQUE INDEX `id_UNIQUE` (`id_revisao` ASC) VISIBLE,
  INDEX `fk_revisao_ordem_de_servico1_idx` (`ordem_de_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_revisao_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id`)
    REFERENCES `os_oficina`.`ordem_de_servico` (`id_ordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`concerto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`concerto` (
  `id_concerto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ordem_de_servico_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_concerto`),
  UNIQUE INDEX `id_UNIQUE` (`id_concerto` ASC) VISIBLE,
  INDEX `fk_concerto_ordem_de_servico1_idx` (`ordem_de_servico_id` ASC) VISIBLE,
  CONSTRAINT `fk_concerto_ordem_de_servico1`
    FOREIGN KEY (`ordem_de_servico_id`)
    REFERENCES `os_oficina`.`ordem_de_servico` (`id_ordem_de_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`mecanico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`mecanico` (
  `idmecanico` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `revisao_id` INT UNSIGNED NOT NULL,
  `concerto_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmecanico`),
  UNIQUE INDEX `idmecanico_UNIQUE` (`idmecanico` ASC) VISIBLE,
  INDEX `fk_mecanico_revisao1_idx` (`revisao_id` ASC) VISIBLE,
  INDEX `fk_mecanico_concerto1_idx` (`concerto_id` ASC) VISIBLE,
  CONSTRAINT `fk_mecanico_revisao1`
    FOREIGN KEY (`revisao_id`)
    REFERENCES `os_oficina`.`revisao` (`id_revisao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mecanico_concerto1`
    FOREIGN KEY (`concerto_id`)
    REFERENCES `os_oficina`.`concerto` (`id_concerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `os_oficina`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `os_oficina`.`veiculo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `mecanico_idmecanico` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_veiculo_mecanico_idx` (`mecanico_idmecanico` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_mecanico`
    FOREIGN KEY (`mecanico_idmecanico`)
    REFERENCES `os_oficina`.`mecanico` (`idmecanico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
