-- MySQL Script generated by MySQL Workbench
-- Thu Sep 22 21:13:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `idveiculo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idveiculo`),
  UNIQUE INDEX `idveiculo_UNIQUE` (`idveiculo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cadastro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cadastro` (
  `idcadastro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idcadastro`),
  UNIQUE INDEX `idcadastro_UNIQUE` (`idcadastro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `veiculo_idveiculo` INT UNSIGNED NOT NULL,
  `cadastro_idcadastro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente`, `veiculo_idveiculo`, `cadastro_idcadastro`),
  UNIQUE INDEX `idCliente_UNIQUE` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Cliente_veiculo_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  INDEX `fk_Cliente_cadastro1_idx` (`cadastro_idcadastro` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_veiculo`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `mydb`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_cadastro1`
    FOREIGN KEY (`cadastro_idcadastro`)
    REFERENCES `mydb`.`cadastro` (`idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa fisica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa fisica` (
  `idpessoa fisica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpessoa fisica`),
  UNIQUE INDEX `idpessoa fisica_UNIQUE` (`idpessoa fisica` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pessoa juridica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pessoa juridica` (
  `idpessoa juridica` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `razao social` VARCHAR(100) NOT NULL,
  `cnpj` VARCHAR(15) NOT NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `nome fantasia` VARCHAR(100) NOT NULL,
  `pessoa fisica_idpessoa fisica` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idpessoa juridica`, `pessoa fisica_idpessoa fisica`),
  UNIQUE INDEX `idpessoa juridica_UNIQUE` (`idpessoa juridica` ASC) VISIBLE,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_pessoa juridica_pessoa fisica1_idx` (`pessoa fisica_idpessoa fisica` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa juridica_pessoa fisica1`
    FOREIGN KEY (`pessoa fisica_idpessoa fisica`)
    REFERENCES `mydb`.`pessoa fisica` (`idpessoa fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo de cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo de cadastro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo de cadastro` (
  `cadastro_idcadastro` INT UNSIGNED NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Cliente_veiculo_idveiculo` INT UNSIGNED NOT NULL,
  `Cliente_cadastro_idcadastro` INT UNSIGNED NOT NULL,
  `pessoa fisica_idpessoa fisica` INT UNSIGNED NOT NULL,
  `pessoa juridica_idpessoa juridica` INT UNSIGNED NOT NULL,
  `pessoa juridica_pessoa fisica_idpessoa fisica` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cadastro_idcadastro`, `Cliente_idCliente`, `Cliente_veiculo_idveiculo`, `Cliente_cadastro_idcadastro`, `pessoa fisica_idpessoa fisica`, `pessoa juridica_idpessoa juridica`, `pessoa juridica_pessoa fisica_idpessoa fisica`),
  INDEX `fk_cadastro_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_veiculo_idveiculo` ASC, `Cliente_cadastro_idcadastro` ASC) VISIBLE,
  INDEX `fk_cadastro_has_Cliente_cadastro1_idx` (`cadastro_idcadastro` ASC) VISIBLE,
  INDEX `fk_tipo de cadastro_pessoa fisica1_idx` (`pessoa fisica_idpessoa fisica` ASC) VISIBLE,
  INDEX `fk_tipo de cadastro_pessoa juridica1_idx` (`pessoa juridica_idpessoa juridica` ASC, `pessoa juridica_pessoa fisica_idpessoa fisica` ASC) VISIBLE,
  CONSTRAINT `fk_cadastro_has_Cliente_cadastro1`
    FOREIGN KEY (`cadastro_idcadastro`)
    REFERENCES `mydb`.`cadastro` (`idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cadastro_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_veiculo_idveiculo` , `Cliente_cadastro_idcadastro`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `veiculo_idveiculo` , `cadastro_idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo de cadastro_pessoa fisica1`
    FOREIGN KEY (`pessoa fisica_idpessoa fisica`)
    REFERENCES `mydb`.`pessoa fisica` (`idpessoa fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo de cadastro_pessoa juridica1`
    FOREIGN KEY (`pessoa juridica_idpessoa juridica` , `pessoa juridica_pessoa fisica_idpessoa fisica`)
    REFERENCES `mydb`.`pessoa juridica` (`idpessoa juridica` , `pessoa fisica_idpessoa fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mecania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mecania` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mecania` (
  `idmecania` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cadastro_idcadastro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idmecania`, `cadastro_idcadastro`),
  UNIQUE INDEX `idmecania_UNIQUE` (`idmecania` ASC) VISIBLE,
  INDEX `fk_mecania_cadastro1_idx` (`cadastro_idcadastro` ASC) VISIBLE,
  CONSTRAINT `fk_mecania_cadastro1`
    FOREIGN KEY (`cadastro_idcadastro`)
    REFERENCES `mydb`.`cadastro` (`idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo por cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veiculo por cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veiculo por cliente` (
  `veiculo_idveiculo` INT UNSIGNED NOT NULL,
  `Cliente_idCliente` INT UNSIGNED NOT NULL,
  `Cliente_veiculo_idveiculo` INT UNSIGNED NOT NULL,
  `Cliente_cadastro_idcadastro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`veiculo_idveiculo`, `Cliente_idCliente`, `Cliente_veiculo_idveiculo`, `Cliente_cadastro_idcadastro`),
  INDEX `fk_veiculo_has_Cliente_Cliente1_idx` (`Cliente_idCliente` ASC, `Cliente_veiculo_idveiculo` ASC, `Cliente_cadastro_idcadastro` ASC) VISIBLE,
  INDEX `fk_veiculo_has_Cliente_veiculo1_idx` (`veiculo_idveiculo` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_has_Cliente_veiculo1`
    FOREIGN KEY (`veiculo_idveiculo`)
    REFERENCES `mydb`.`veiculo` (`idveiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_idCliente` , `Cliente_veiculo_idveiculo` , `Cliente_cadastro_idcadastro`)
    REFERENCES `mydb`.`Cliente` (`idCliente` , `veiculo_idveiculo` , `cadastro_idcadastro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`servico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `mecania_idmecania` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idservico`, `mecania_idmecania`),
  UNIQUE INDEX `idservico_UNIQUE` (`idservico` ASC) VISIBLE,
  INDEX `fk_servico_mecania1_idx` (`mecania_idmecania` ASC) VISIBLE,
  CONSTRAINT `fk_servico_mecania1`
    FOREIGN KEY (`mecania_idmecania`)
    REFERENCES `mydb`.`mecania` (`idmecania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valor da peca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`valor da peca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`valor da peca` (
  `idvalor da peca` INT NOT NULL AUTO_INCREMENT,
  `servico_idservico` INT NOT NULL,
  `servico_mecania_idmecania` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idvalor da peca`, `servico_idservico`, `servico_mecania_idmecania`),
  UNIQUE INDEX `idvalor da peca_UNIQUE` (`idvalor da peca` ASC) VISIBLE,
  INDEX `fk_valor da peca_servico1_idx` (`servico_idservico` ASC, `servico_mecania_idmecania` ASC) VISIBLE,
  CONSTRAINT `fk_valor da peca_servico1`
    FOREIGN KEY (`servico_idservico` , `servico_mecania_idmecania`)
    REFERENCES `mydb`.`servico` (`idservico` , `mecania_idmecania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`motor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`motor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`motor` (
  `idmotor` INT NOT NULL AUTO_INCREMENT,
  `radiator` FLOAT NOT NULL,
  `valvula` FLOAT NOT NULL,
  `biela` FLOAT NOT NULL,
  `bloco` FLOAT NOT NULL,
  PRIMARY KEY (`idmotor`),
  UNIQUE INDEX `idmotor_UNIQUE` (`idmotor` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interior`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`interior` ;

CREATE TABLE IF NOT EXISTS `mydb`.`interior` (
  `idinterior` INT NOT NULL AUTO_INCREMENT,
  `direcao` FLOAT NOT NULL,
  `ar` FLOAT NOT NULL,
  `banco` FLOAT NOT NULL,
  `eletronica` FLOAT NULL,
  PRIMARY KEY (`idinterior`),
  UNIQUE INDEX `idinterior_UNIQUE` (`idinterior` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`local de concerto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`local de concerto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`local de concerto` (
  `idlocal de concerto` INT NOT NULL AUTO_INCREMENT,
  `valor da peca_idvalor da peca` INT NOT NULL,
  `valor da peca_servico_idservico` INT NOT NULL,
  `valor da peca_servico_mecania_idmecania` INT UNSIGNED NOT NULL,
  `motor_idmotor` INT NOT NULL,
  `interior_idinterior` INT NOT NULL,
  PRIMARY KEY (`idlocal de concerto`, `valor da peca_idvalor da peca`, `valor da peca_servico_idservico`, `valor da peca_servico_mecania_idmecania`, `motor_idmotor`, `interior_idinterior`),
  UNIQUE INDEX `idlocal de concerto_UNIQUE` (`idlocal de concerto` ASC) VISIBLE,
  INDEX `fk_local de concerto_valor da peca1_idx` (`valor da peca_idvalor da peca` ASC, `valor da peca_servico_idservico` ASC, `valor da peca_servico_mecania_idmecania` ASC) VISIBLE,
  INDEX `fk_local de concerto_motor1_idx` (`motor_idmotor` ASC) VISIBLE,
  INDEX `fk_local de concerto_interior1_idx` (`interior_idinterior` ASC) VISIBLE,
  CONSTRAINT `fk_local de concerto_valor da peca1`
    FOREIGN KEY (`valor da peca_idvalor da peca` , `valor da peca_servico_idservico` , `valor da peca_servico_mecania_idmecania`)
    REFERENCES `mydb`.`valor da peca` (`idvalor da peca` , `servico_idservico` , `servico_mecania_idmecania`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local de concerto_motor1`
    FOREIGN KEY (`motor_idmotor`)
    REFERENCES `mydb`.`motor` (`idmotor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_local de concerto_interior1`
    FOREIGN KEY (`interior_idinterior`)
    REFERENCES `mydb`.`interior` (`idinterior`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
